[package]
description = "Native input-method-engine integration for ROSACE"
name = "rosace-ime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-trace = { path = "../rosace-trace", version = "0.1.0" }
