[workspace]
members = [
    "rosace",
    "rosace-macros",
    "rosace-view-syntax",
    "rosace-style",
    "rosace-trace",
    "rosace-core",
    "rosace-state",
    "rosace-layout",
    "rosace-render",
    "rosace-theme",
    "rosace-widgets",
    "rosace-cli",
    "rosace-asset-codegen",
    "rosace-platform",
    "rosace-animate",
    "rosace-nav",
    "rosace-hot-reload",
    "rosace-devtools",
    "rosace-net",
    "rosace-storage",
    "rosace-text",
    "rosace-shader",
    "rosace-media",
    "rosace-test-utils",
    "rosace-compositor",
    "rosace-ffi",
    "rosace-thirdparty-material-test",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["ROSACE Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rosace-ui/rosace"
readme = "README.md"
