[package]
description = "GPU/CPU hybrid renderer for ROSACE with dirty-region tracking"
name = "rosace-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-trace  = { path = "../rosace-trace", version = "0.1.0" }
rosace-core   = { path = "../rosace-core", version = "0.1.0" }
rosace-layout = { path = "../rosace-layout", version = "0.1.0" }
rosace-macros = { path = "../rosace-macros", version = "0.1.0" }
tiny-skia      = "0.11"
swash          = "0.2"
ttf-parser     = "0.20"
