[package]
description = "Internationalization primitives for ROSACE"
name = "rosace-i18n"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rosace-state = { path = "../rosace-state", version = "0.1.0" }
rosace-trace = { path = "../rosace-trace", version = "0.1.0" }
