[package]
description = "Text input widgets for ROSACE: TextInput, TextArea, OS IME integration"
name = "rosace-text"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rosace-core   = { path = "../rosace-core", version = "0.1.0" }
rosace-render = { path = "../rosace-render", version = "0.1.0" }
rosace-theme  = { path = "../rosace-theme", version = "0.1.0" }
