[package]
description = "Route transition animations for ROSACE navigation"
name = "rosace-nav-anim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-nav     = { path = "../rosace-nav", version = "0.1.0" }
rosace-trace   = { path = "../rosace-trace", version = "0.1.0" }
