[package]
description = "Event bus, ring buffer, and flight-recorder logging framework for ROSACE"
name = "rosace-trace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
web-time = "1"
