[package]
description = "Headless test utilities for ROSACE widget and rendering tests"
name = "rosace-test-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-render   = { path = "../rosace-render", version = "0.1.0" }
rosace-platform = { path = "../rosace-platform", version = "0.1.0" }
rosace-core     = { path = "../rosace-core", version = "0.1.0" }
