[package]
description = "Animation primitives and hooks for ROSACE: Tween, Timeline, easing"
name = "rosace-animate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
web-time = "1"
rosace-core  = { path = "../rosace-core", version = "0.1.0" }
rosace-state = { path = "../rosace-state", version = "0.1.0" }
rosace-trace = { path = "../rosace-trace", version = "0.1.0" }
