[package]
description = "File-watching and rebuild primitive powering ROSACE's hot reload"
name = "rosace-hot-reload"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rosace-trace = { path = "../rosace-trace", version = "0.1.0" }
