[package]
description = "Text shaping for ROSACE"
name = "rosace-shaping"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rosace-core   = { path = "../rosace-core", version = "0.1.0" }
rosace-render = { path = "../rosace-render", version = "0.1.0" }
rosace-text   = { path = "../rosace-text", version = "0.1.0" }
rosace-trace  = { path = "../rosace-trace", version = "0.1.0" }
