[package]
description = "Style primitive types for ROSACE (pre-integration)"
name = "rosace-style"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-theme  = { path = "../rosace-theme", version = "0.1.0" }
rosace-core   = { path = "../rosace-core", version = "0.1.0" }
