[package]
description = "rsc: the ROSACE CLI for scaffolding, running, building, and analyzing apps"
name = "rosace-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "rsc"
path = "src/main.rs"

[dependencies]
rosace-trace      = { path = "../rosace-trace", version = "0.1.0" }
rosace-core       = { path = "../rosace-core", version = "0.1.0" }
rosace-hot-reload = { path = "../rosace-hot-reload", version = "0.1.0" }
resvg = { version = "0.47.0", default-features = false }
