[package]
description = "Navigator, router, and route stack for ROSACE"
name = "rosace-nav"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rosace-animate = { path = "../rosace-animate", version = "0.1.0" }
rosace-core    = { path = "../rosace-core", version = "0.1.0" }
rosace-state   = { path = "../rosace-state", version = "0.1.0" }
rosace-theme   = { path = "../rosace-theme", version = "0.1.0" }
rosace-trace   = { path = "../rosace-trace", version = "0.1.0" }
